### ISSUE TITLE
Add a way to skip tests

### ISSUE THREAD

**Issue by colearendt** [rstudio/dbtest#13]
It would be nice to have a way to skip tests (in the native `testthat` way... maybe by parsing the "verb" and putting "skip mutate" or something).  This would give a better picture in the testthat output than commented YAML, for instance.

**Comment by colearendt** [comment]
Best "not-over-engineered" approach we came up with was a separate YAML file (`skip-tests.yml`) that would allow skipping based on: 
* context
* verb
* database

The latter may be tricky...somehow check out what text might uniquely identify a `DBI` interface for comparison to inject the skipping.

**Comment by colearendt** [comment]
Not a great way to determine database other than `class(tbl_sql$src$con)`, which we already use... so we will just go with that.  The first pass worked alright...

**Comment by colearendt** [comment]
Finished a naive implementation... this is what plot output looks like:
![image](https://user-images.githubusercontent.com/23075542/42292768-d863daaa-7fa2-11e8-8460-985e3405ba57.png)

And the skip file:
```yaml
- text: not currently implemented
  db: pg
  file: logical-control
  context: pmin
  test:
    - summarize
    - mutate
- text: not currently implemented
  db: pg
  file: logical-control
  context: pmax
  test:
    - summarize
    - mutate
- text: not currently implemented
  db: pg
  file: logical-control
  context: ifelse
- text: not currently implemented
  db: oracle
  context: desc
- text: skip a whole row
  file: logical-control
  context: c
  test:
    - summarize
- text: skip many rows together
  file: logical-control
  context: pmax_local

- text: skip entire db
  file: logical-control
  db: mssql

```
