### ISSUE TITLE
Bad YAML test syntax throws cryptic error in `plot_tests`

### ISSUE THREAD

**Issue by colearendt** [rstudio/dbtest#19]
If the YAML syntax is bad, then the test suite will run, but the format is different enough that `plot_tests` will fail with a cryptic error message that is very challenging to debug.

```
 Error in data.frame(file = test$file, context = context, test = test$test,  : 
  arguments imply differing number of rows: 1, 2 
```

The YAML that generated the bad test results (for repro):
```yaml
- test-tolower:
    mutate: tolower(fld_character)
    group_by: tolower(fld_character)
  test-toupper:
    mutate: toupper(fld_character)
    group_by: toupper(fld_character)
```

You can generate that YAML file with:
```r
test_file <- fs::path_temp("test-file.yml")
yaml::write_yaml(
  list(
    setNames(
    list(
      list(
        "mutate" = "tolower(fld_character)"
        , "group_by" = "tolower(fld_character)"
      )
      , list(
        "mutate" = "toupper(fld_character)"
        , "group_by" = "toupper(fld_character)"
      )
    )
    , c("test-tolower", "test-toupper")
  ))
  , file = test_file
)
```

And then that just needs to be executed as follows:
```r
test_results <- dbtest::test_databases("conn.yml", test_file)
dbtest::plot_tests(test_results)
```

Fix would be a better error message, better recovery from bad YAML tests, or something of the like.
