### ISSUE TITLE
Something in the tests ruins the connection object

### ISSUE THREAD

**Issue by colearendt** [rstudio/dbtest#3]
Not sure what is happening here.  Something with a transaction not being cleaned up properly.  Maybe problems with the `rollback`?

```r
con <- dbConnect(odbc(), "pg")
test_results <- test_single_database(con)
# ...F....F....F....F....FF...F....F.F.EEEEEE
dbGetQuery(con, "select * from information_schema.tables")
#Error in new_result(connection@ptr, statement) : 
#  nanodbc/nanodbc.cpp:1344: 25P02: [RStudio][PostgreSQL] (30) Error occurred while trying to execute a query: [SQLState 25P02] ERROR:  current transaction is aborted, commands ignored until end of transaction block
 
con
#<OdbcConnection> postgres@postgres
#  Database: postgres
#  PostgreSQL Version: 10.2.0
```

**Comment by edgararuiz** [comment]
Thanks @colearendt - Would you mind posting or sending me the yml file with the tests?

**Comment by colearendt** [comment]
Sure thing.  Thanks for pointing that out.  I just tried with an all successful batch of tests (not `E`) and nothing goes awry with the connection.  I expect that the culprit is ending on the `E`, or an `E` occurring and not being cleaned up properly (error on the database side that needs to have the transaction closed or rolled back).

I will take a look.  The test yaml will be a part of a PR I will submit shortly, so it probably won't reproduce the same on master at present.  

```yaml
- round:
    mutate: round(fld_double, 0)
    filter: round(fld_double, 0) > 1
    summarise: sum(round(fld_double, 0), na.rm = TRUE)
    group_by: round(fld_double, 0)
    arrange: round(fld_double, 0)
- add:
    mutate: fld_double + fld_integer
    filter: fld_double + fld_integer < 10
    summarise: sum(fld_double + fld_integer, na.rm=TRUE)
    group_by: fld_double + fld_integer
    arrange: fld_double + fld_integer
- subtract:
    mutate: fld_double - fld_integer
    filter: fld_double - fld_integer < 1
    summarise: sum(fld_double - fld_integer, na.rm=TRUE)
    group_by: fld_double - fld_integer
    arrange: fld_double - fld_integer
- multiply:
    mutate: fld_double * fld_integer
    filter: fld_double * fld_integer < 10
    summarise: sum(fld_double * fld_integer, na.rm=TRUE)
    group_by: fld_double * fld_integer
    arrange: fld_double * fld_integer
- divide:
    mutate: fld_double / fld_integer
    filter: fld_double / fld_integer < 10
    summarise: sum(fld_double / fld_integer, na.rm=TRUE)
    group_by: fld_double / fld_integer
    arrange: fld_double / fld_integer
- power:
    mutate: fld_double ^ fld_integer
    filter: fld_double ^ fld_integer < 10
    summarise: sum(fld_double ^ fld_integer, na.rm=TRUE)
    group_by: fld_double ^ fld_integer
    arrange: fld_double ^ fld_integer
- remainder:
    mutate: (2 * fld_integer) %% (fld_integer + 1)
    filter: (2 * fld_integer) %% (fld_integer + 1) < 5
    summarise: sum((2 * fld_integer) %% (fld_integer + 1), na.rm=TRUE)
    group_by: (2 * fld_integer) %% (fld_integer + 1)
    arrange: (2 * fld_integer) %% (fld_integer + 1)
- bool_neq:
    mutate: fld_integer != fld_double
    filter: fld_integer != fld_double
    summarise: sum(fld_integer != fld_double, na.rm=TRUE)
    group_by: fld_integer != fld_double
- bool_neq_same:
    mutate: fld_integer != fld_integer
    filter: fld_integer != fld_integer
    summarise: sum(fld_integer != fld_integer, na.rm=TRUE)
    group_by: fld_integer != fld_integer

```

**Comment by colearendt** [comment]
Confirmed which test does this.  It is the `summarise` within `bool_neq`

```
obj %>% summarize(sum(fld_integer != fld_double, na.rm=TRUE)) %>% pull()
#Error in new_result(connection@ptr, statement) : 
#  nanodbc/nanodbc.cpp:1344: 25P02: [RStudio][PostgreSQL] (30) Error occurred while trying to #execute a query: [SQLState 25P02] ERROR:  current transaction is aborted, commands ignored until #end of transaction block
```

Ultimately, the concern here is that one test should not be able to fail others, so there needs to be some way of sandboxing tests (without reinitiating the connection, obviously).  Why does this test create a transaction?

**Comment by edgararuiz** [comment]
Ok, can we confirm that the subsequent set of tests are successful? I think we need to if the `EEEE` are false negatives

```
- bool_neq_same:
    mutate: fld_integer != fld_integer
    filter: fld_integer != fld_integer
    summarise: sum(fld_integer != fld_integer, na.rm=TRUE)
    group_by: fld_integer != fld_integer
```
